


INSERT INTO SPTRANS.SPT_MODULE (MODULE_ID,NAME,DESCRIPTION,PARENT_ID,MODAL_CONSTRAINT_ID,MIN_GROUP_LEVEL_ID,MODULE_TYPE_ID,MODULE_STATUS_ID)
                VALUES ('2000','PERSO_CONSULTAR','Consulta as personalizações de cartões referente a determinada empresa','10','1','0','1','1');
                
INSERT INTO SPTRANS.SPT_MODULE (MODULE_ID,NAME,DESCRIPTION,PARENT_ID,MODAL_CONSTRAINT_ID,MIN_GROUP_LEVEL_ID,MODULE_TYPE_ID,MODULE_STATUS_ID)
                VALUES ('2001','PERSO_PERSONALIZAR','Personaliza cartões referente a determinada empresa','2000','1','0','2','1');

INSERT INTO SPTRANS.SPT_RIGHTS (OPERATOR_GROUP_ID,MODULE_ID) VALUES (1,2000); 

COMMIT;